### ISSUE TITLE
Will that extension work on messenger.com website?

### ISSUE THREAD

**Issue by iMrDJAi** [Leyka/messenger-unseen#1]
[Title]

**Comment by iMrDJAi** [comment]
Never mind, tested and it's working fine 😀
What about making an extension for Instagram? ❤

**Comment by Leyka** [comment]
Hey @iMrDJAi 
I can do some tests in the near future and try to adapt it to Instagram also 👍

**Comment by iMrDJAi** [comment]
And you should try to make it work on chromium browsers too 😄
