### ISSUE TITLE
Doesn't work after the recent messenger update

### ISSUE THREAD

**Issue by Thanatoslayer6** [Leyka/messenger-unseen#2]
It seems like the extension stopped working for a while now, it's been 4-5 days after the latest update in messenger.com site, affecting its interface. I guess that's the cause of this issue maybe there is some slight change of code in their website???

I'm using Firefox ESR 78.5.0 x64 and also I tested out on different Firefox versions including the latest one.... It just doesn't work anymore any help?

**Comment by Leyka** [comment]
This extension is no longer supported since new Facebook/Messenger update switching to GraphQL.
Sorry for any inconvenience
